apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services_shared_key
spec:
  selector:
    app: nginx
  ports:
    - port: 22
      name: ssh
    - port: 80
      name: http
    - port: 443
      name: https
  type: LoadBalancer
  loadBalancerIP: 192.168.99.240

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ft_services_nginx
          imagePullPolicy: Never
          ports:
            - containerPort: 22
            - containerPort: 80
            - containerPort: 443
          livenessProbe:
            tcpSocket:
              port: 22
            initialDelaySeconds: 4
            periodSeconds: 4
