apiVersion: v1
kind: Service
metadata:
  annotations:
      metallb.universe.tf/address-pool: default
  name: ftps
  labels:
      app: ftps
spec:
  ports:
  - name: data
    port: 20
    targetPort: 20
  - name: ftps
    port: 21
    targetPort: 21
    protocol: TCP
  - name: ftps-passive
    port: 30000
    targetPort: 30000
    protocol: TCP
  selector:
    app: ftps
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 30000
