apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services_shared_key
spec:
  selector:
    app: ftps
  ports:
    - port: 20
      name: ftps-data
    - port: 21
      name: ftps
    - port: 30000
      name: ftps-passive
  type: LoadBalancer
  loadBalancerIP: 192.168.99.240

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ft_services_ftps
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 30000
          livenessProbe:
            tcpSocket:
              port: 21
            initialDelaySeconds: 4
            periodSeconds: 4
