name: CI
on:   
  - pull_request
  - push
jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1
    steps:
    - uses: actions/checkout@v2
    - run: minikube start 
      id: minikube
    # now you can run kubectl to see the pods in the cluster
    - name: kubectl 
      run: kubectl get pods -A
    - name: setup
      run: bash setup.sh
